SELECT DISTINCT(CRCC.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR CRCC
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
    ON CRCC.CAR_ID = CRCRH.CAR_ID
WHERE CAR_TYPE = '세단'
AND MONTH(START_DATE) = 10
ORDER BY CRCC.CAR_ID DESC

/* 
✅ 스스로 풀었는가?
☑️ 소요 시간 : 2분

✅ 리뷰
- 

✅ 알아두기
- 
*/