SELECT
    CASE
    WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 1 AND 3
        THEN '1Q'
    WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 4 AND 6
        THEN '2Q'
    WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 7 AND 9
        THEN '3Q'
    WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 10 AND 12
        THEN '4Q' 
    END AS QUARTER,
    COUNT(*) AS ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY QUARTER
ORDER BY QUARTER

/* 
✅ 스스로 풀었는가?
☑️ 소요 시간 : 문제 읽고 바로 풀었음

✅ 리뷰
- 

✅ 알아두기
- 
*/