SELECT 
    CAR_ID,
    ROUND(AVG(DATEDIFF(END_DATE, START_DATE)+1), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC

/* 
✅ 스스로 풀었는가?
☑️ 소요 시간 : 7분

✅ 리뷰
- START_DATE == END_DATE 인 경우에도 대여기간 1이므로 DATEDIFF 함수 결과에 1 을 더해줌

✅ 알아두기
-
*/