SELECT
    PARENT.ID,
    CASE WHEN CHILD.PARENT_ID IS NULL
    THEN 0
    ELSE COUNT(PARENT.ID) END
    AS CHILD_COUNT
FROM ECOLI_DATA AS CHILD
RIGHT JOIN ECOLI_DATA AS PARENT
ON CHILD.PARENT_ID = PARENT.ID
GROUP BY PARENT.ID
ORDER BY PARENT.ID

-- 표 그려보면서 풀었더니 조금 감이 왔던 문제
-- 다만 RIGHT JOIN하면서 자식이 없는 ID도 하나씩은 카운트가 되어서, 이를 CASE WHEN으로 필터링하여 0으로 설정해주었다.
-- CASE WHEN 구문 사용 방법은 찾아봤다