WITH RECURSIVE T1 AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT T2.ID, T2.PARENT_ID, GENERATION + 1 AS GENERATION
    FROM T1
    JOIN ECOLI_DATA AS T2 ON T1.ID = T2.PARENT_ID
)
SELECT COUNT(ID) AS COUNT, GENERATION
FROM T1
WHERE ID NOT IN (
    SELECT DISTINCT PARENT_ID
    FROM T1
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY 2
ORDER BY 2

-- 1세대 대장균(PARENT_ID IS NULL)을 초깃값으로 설정한 후 재귀
-- 세대가 없는 대장균을 찾기 위해 WHERE ID NOT IN 사용