SELECT CHILD.ID, CHILD.GENOTYPE, PARENT.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS CHILD
INNER JOIN ECOLI_DATA AS PARENT
ON CHILD.PARENT_ID = PARENT.ID
AND CHILD.GENOTYPE & PARENT.GENOTYPE = PARENT.GENOTYPE
ORDER BY CHILD.ID

-- ID도 서로 같은지 확인할 것