SELECT 
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    ED1_MAX - SIZE_OF_COLONY AS YEAR_DEV,
    ID
FROM ECOLI_DATA ED
JOIN (
    SELECT YEAR(ED1.DIFFERENTIATION_DATE) AS ED1_YEAR, MAX(ED1.SIZE_OF_COLONY) AS ED1_MAX
    FROM ECOLI_DATA ED1
    GROUP BY YEAR(ED1.DIFFERENTIATION_DATE)
) AS ED_TEMP 
ON YEAR(ED.DIFFERENTIATION_DATE) = ED_TEMP.ED1_YEAR
ORDER BY ED_TEMP.ED1_YEAR, YEAR_DEV

/* 
✅ 스스로 풀었는가?
❌ 소요 시간 : 30분

✅ 리뷰
1. 원래 아래와 같은 쿼리로 생각했음
SELECT 
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    (
        SELECT MAX(ED1.SIZE_OF_COLONY)
        FROM ECOLI_DATA ED1
        GROUP BY YEAR(ED1.DIFFERENTIATION_DATE)
        HAVING YEAR(ED1.DIFFERENTIATION_DATE) = YEAR  -- A)
    ) - SIZE_OF_COLONY,
    ID
FROM ECOLI_DATA ED 
- 하지만 GROUP BY 로 이미 그룹핑된 이후이므로, A) HAVING 절에서 ED1.DIFFERENTIATION_DATE 에 대해 알지 못하므로 오류 발생

2. 다른 사람 풀이 참고해서 다시 풀어봄.
- (YEAR, MAX) 에 대한 테이블을 따로 만들어서 YEAR 기준으로 JOIN
- 조인한 테이블에서 MAX 값을 참조하여 계산

✅ 알아두기
- 
*/