SELECT ID, FISH_NAME, FISH_INFO.LENGTH AS LENGTH
FROM FISH_INFO NATURAL JOIN FISH_NAME_INFO
WHERE FISH_INFO.FISH_TYPE IN 
(
    SELECT FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING LENGTH = MAX(LENGTH)
)
ORDER BY ID

-- 서브 쿼리 사용이 핵심이었던 문제