SELECT
    FP.PRODUCT_ID,
    FP.PRODUCT_NAME,
    SUM(AMOUNT) * FP.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT FP
JOIN FOOD_ORDER FO
    ON FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE YEAR(PRODUCE_DATE) = 2022 
    AND MONTH(PRODUCE_DATE) = 5
GROUP BY FP.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID

/* 
✅ 스스로 풀었는가?
☑️ 소요 시간 : 9분

✅ 리뷰
- FOOD_PRODUCT <> FOOD_ORDER 조인 시 FOOD_ORDER 에 PRODUCT_ID 에 대한 여러 행이 존재할 수 있음
- 따라서 GROUP BY 절로 PRODUCT_ID 에 해당하는 AMOUNT 의 합계를 구한 후 PRICE 를 곱해서 총 금액을 구해야 함

✅ 알아두기
-

*/